site_name: 浩哈哈哈哈
theme: 
  name: material
  icon:
    logo: material/library
  palette:
    - scheme: slate # 夜间模式
      primary: deep purple
      accent: deep orange
      toggle:
        icon: material/weather-sunny
        name: 切换至日间模式
    - scheme: default # 日间模式
      primary: deep purple # 上方的
      accent: deep orange # 链接等可交互元件的高亮色
      toggle:
        icon: material/weather-night # 图标
        name: 切换至夜间模式 # 鼠标悬浮提示
  features:
    - navigation.tabs
    - navigation.top
    - navigation.indexes
    - navigation.expand
    - search.suggest
    - search.highlight
    - content.code.copy
  language: zh

edit_uri: edit/main/docs

nav:
  - 主页: http://haohaha.cn
  - 算法打卡: http://alg.haohaha.cn
  - 数学笔记: http://math.haohaha.cn
  - 英语笔记: http://eng.haohaha.cn
  - CS笔记: 
    - index.md
    - GreenHand菜鸟:
      - 操作系统和体系结构方向招生简介: greenhand/recruit/recruit.md
      - 个人成长路线-beta: greenhand/fertile/fertile.md
      - Ubuntu 22.04 虚拟机搭建全流程: greenhand/Ubuntu2204-greenhand/Ubuntu2204-greenhand.md
      - Ubuntu 22.04 我的第一台实体机: greenhand/Ubuntu2204-myFirstPhysicalLinuxMachine/U2204-mFPLM.md
      - 博客维护教程-文案工作部分: greenhand/Blog_Maintainance_CW/Blog_Maintenance-Content_Workers.md
      - 信息的编解码能力: greenhand/de-en-code/de-en-code-info.md
      - 提问小习题: greenhand/ask-question-zbt/ask-zbt.md
    - 408:
      - arch:
        - 1.计算机系统概述:
          - 1.1_计算机发展历程: 408/arch/1-1.md
          - 1.2_计算机系统层次结构: 408/arch/1-2.md
          - 1.3_计算机的性能指标: 408/arch/1-3.md
        - 2.数据的表示与运算:
          - 2.1_数制与编码: 408/arch/2-1.md
          - 2.2_运算方法和运算电路: 408/arch/2-2.md
          - 2.3_浮点数的表示与运算: 408/arch/2-3.md
        - 3.存储系统:
          - 3.1_存储器概述: 408/arch/3-1.md
          - 3.2_主存储器: 408/arch/3-2.md
          - 3.3_主存储器与CPU的连接: 408/arch/3-3.md
          - 3.4_外部存储器: 408/arch/3-4.md
          - 3.5_高速缓冲存储器: 408/arch/3-5.md
          - 3.6_虚拟存储器: 408/arch/3-6.md
        - 4.指令系统:
          - 4.1_指令格式: 408/arch/4-1.md
          - 4.2_指令的寻址方式: 408/arch/4-2.md
          - 4.3_程序的机器级代码表示: 408/arch/4-3.md
          - 4.4_CISC和RISC的基本概念: 408/arch/4-4.md
        - 5.中央处理器:
          - 5.1_CPU的功能和基本结构: 408/arch/5-1.md
          - 5.2_指令执行过程: 408/arch/5-2.md
          - 5.3_数据通路的功能和基本结构: 408/arch/5-3.md
          - 5.4_控制器的功能和工作原理: 408/arch/5-4.md
          - 5.5_异常和中断机制: 408/arch/5-5.md
          - 5.6_指令流水线: 408/arch/5-6.md
          - 5.7_多处理器的基本概念: 408/arch/5-7.md
        - 6.总线:
          - 6.1_总线概述: 408/arch/6-1.md
          - 6.2_总线事务和定时: 408/arch/6-2.md
        - 7.输入/输出系统:
          - 7.1_I/O系统基本概念: 408/arch/7-1.md
          - 7.2_I/O接口: 408/arch/7-2.md
          - 7.3_I/O方式: 408/arch/7-3.md
      - os:
        - 1.计算机系统概述:
#         - 1.1_操作系统的基本概念: 408/os/1-1.md
#         - 1.2_操作系统发展历程: 408/os/1-2.md
#         - 1.3_操作系统运行环境: 408/os/1-3.md
#         - 1.4_操作系统结构: 408/os/1-4.md
          - 1.5_操作系统引导: 408/os/1-5.md
          - 1.6_虚拟机: 408/os/1-6.md
        - 2.进程与线程:
          - 2.1_进程与线程: 408/os/2-1.md
          - 2.2_处理机调度: 408/os/2-2.md
#         - 2.3_同步与互斥: 408/os/2-3.md
#         - 2.4_死锁: 408/os/2-4.md
        - 3.内存管理: 
          - 3.1_内存管理概念: 408/os/3-1.md
          - 3.2_虚拟内存管理: 408/os/3-2.md
        - 4.文件管理: 
          - 4.1_文件系统基础: 408/os/4-1.md
          - 4.2_目录: 408/os/4-2.md
          - 4.3_文件系统: 408/os/4-3.md
        - 5.输入/输出（I/O）管理: 
#         - 5.1_I/O管理概述: 408/os/5-1.md
#         - 5.2_设备独立性软件: 408/os/5-2.md
          - 5.3_磁盘和固态硬盘: 408/os/5-3.md
      - nwk:
#       - 1.计算机网络体系结构:
#         - 1.1_计算机网络概述: 408/nwk/1-1.md
#         - 1.2_计算机网络体系结构与参与模型: 408/mwk/1-2.md
#       - 2.物理层:
#         - 2.1_通信基础: 408/nwk/2-1.md
#         - 2.2_传输介质: 408/nwk/2-2.md
#         - 2.3_物理层设备: 408/nwk/2-3.md
        - 3.数据链路层:
          - 3.1_数据链路层的功能: 408/nwk/3-1.md
          - 3.2_组帧: 408/nwk/3-2.md
#         - 3.3_差错控制: 408/nwk/3-3.md
#         - 3.4_流量控制与可靠传输机制: 408/nwk/3-4.md
#         - 3.5_介质访问控制: 408/nwk/3-5.md
#         - 3.6_局域网: 408/nwk/3-6.md
#         - 3.7_广域网: 408/nwk/3-7.md
#         - 3.8_数据链路层设备: 408/nwk/3-8.md
#       - 4.网络层:
#         - 4.1_网络层的功能: 408/nwk/4-1.md
#         - 4.2_路由算法: 408/nwk/4-2.md
#         - 4.3_IPv4: 408/nwk/4-3.md
#         - 4.4_IPv6: 408/nwk/4-4.md
#         - 4.5_路由协议: 408/nwk/4-5.md
#         - 4.6_IP组播: 408/nwk/4-6.md
#         - 4.7_移动IP: 408/nwk/4-7.md
#         - 4.8_网络层设备: 408/nwk/4-8.md
#       - 5.传输层:
#         - 5.1_传输层提供的服务: 408/nwk/5-1.md
#         - 5.2_UDP协议: 408/nwk/5-2.md
#         - 5.3_TCP协议: 408/nwk/5-3.md
#       - 6.应用层:
#         - 6.1_网络应用模型: 408/nwk/6-1.md
#         - 6.2_域名系统(DNS): 408/nwk/6-2.md
#         - 6.3_文件传输协议(FTP): 408/nwk/6-3.md
#         - 6.4_电子邮件: 408/nwk/6-4.md
#         - 6.5_万维网(WWW): 408/nwk/6-5.md
#     - dsa:
#       - 1.绪论:
#         - 1.1_数据结构的基本概念: 408/dsa/1-1.md
#         - 1.2_算法和算法评价: 408/dsa/1-2.md
#       - 2.线性表:
#         - 2.1_线性表的定义和基本操作: 408/dsa/2-1.md
#         - 2.2_线性表的顺序表示: 408/dsa/2-2.md
#         - 2.3_线性表的链式表示: 408/dsa/2-3.md
#       - 3.栈、队列和数组:
#         - 3.1_栈: 408/dsa/3-1.md
#         - 3.2_队列: 408/dsa/3-2.md
#         - 3.3_栈和队列的应用: 408/dsa/3-3.md
#         - 3.4_数组和特殊矩阵: 408/dsa/3-4.md
#       - 4.串:
#         - 4.1_串的定义和实现: 408/dsa/4-1.md
#         - 4.2_串的模式匹配: 408/dsa/4-2.md
#       - 5.树与二叉树:
#         - 5.1_树的基本概念: 408/dsa/5-1.md
#         - 5.2_二叉树的概念: 408/dsa/5-2.md
#         - 5.3_二叉树的遍历和线索二叉树: 408/dsa/5-3.md
#         - 5.4_树、森林: 408/dsa/5-4.md
#         - 5.5_树与二叉树的应用: 408/dsa/5-5.md
#       - 6.图:
#         - 6.1_图的基本概念: 408/dsa/6-1.md
#         - 6.2_图的存储及基本操作: 408/dsa/6-2.md
#         - 6.3_图的遍历: 408/dsa/6-3.md
#         - 6.4_图的应用: 408/dsa/6-4.md
#       - 7.查找:
#         - 7.1_查找的基本概念: 408/dsa/7-1.md
#         - 7.2_顺序查找和折半查找: 408/dsa/7-2.md
#         - 7.3_树型查找: 408/dsa/7-3.md
#         - 7.4_B树和B+树: 408/dsa/7-4.md
#         - 7.5_散列表: 408/dsa/7-5.md
#       - 8.排序:
#         - 8.1_排序的基本概念: 408/dsa/8-1.md
#         - 8.2_插入排序: 408/dsa/8-2.md
#         - 8.3_交换排序: 408/dsa/8-3.md
#         - 8.4_选择排序: 408/dsa/8-4.md
#         - 8.5_归并排序和基数排序: 408/dsa/8-5.md
#         - 8.6_各种内部排序算法的比较及应用: 408/dsa/8-6.md
#         - 8.7_外部排序: 408/dsa/8-7.md
#   - HJCPP: 
#     - 01.OOP1: hjcpp/01.md
    - MicroFrank:  
      - MySQL:  
        - 01.MySQL安装与初始化: frank/mysql/01.md 
        - 02.数据库的基本操作: frank/mysql/02.md 
        - 03.表的基本操作: frank/mysql/03.md
        - 04.数据操作: frank/mysql/04.md
        - 05.数据类型: frank/mysql/05.md
    - Git:
      - 多分支仓库的创建与上传: git/2023-05-12_git_branch.md
    - 学术会议记录: 
      - 简介: conferenceNotes/index.md
      - 大力开展基于国产AI芯片的大模型系统的研究: conferenceNotes/大力开展基于国产AI芯片的大模型系统的研究.md
#   - Linux高性能服务器编程: 
#     - 第一篇 TCP/IP详解: 
#       - 第1章 TCP/IP协议族: hpsc/01/01.md 
  - 我爱OS: http://os.haohaha.cn 
  - 闲聊波尔卡: http://chat.haohaha.cn 

extra_css:
  - mkdocs/css/no-footer.css # 不使用底部的翻页

markdown_extensions:
    - admonition
    - pymdownx.details
    - pymdownx.superfences

extra:
  homepage: http://haohaha.cn
  social: # icons
    - icon: fontawesome/brands/bilibili
      link: https://space.bilibili.com/1436476753
      name: Bilibili | 浩哈哈哈哈 # 鼠标悬浮提示
    - icon: fontawesome/brands/github
      link: https://github.com/Haohahahaha
      name: GitHub | Haohahahaha
## [bottom-left corner]
copyright: Copyright &copy; 2022-现在 浩哈哈哈哈_ # 左下角的版权声明
