site_name: CS笔记
theme: 
  name: material
  icon:
    logo: material/library
  palette:
    - scheme: slate # 夜间模式
      primary: indigo
      accent: orange
      toggle:
        icon: material/weather-sunny
        name: 切换至日间模式
    - scheme: default # 日间模式
      primary: indigo # 上方的
      accent: orange # 链接等可交互元件的高亮色
      toggle:
        icon: material/weather-night # 图标
        name: 切换至夜间模式 # 鼠标悬浮提示
  features:
    - navigation.tabs
    - navigation.top
    - navigation.indexes
    - navigation.expand
    - search.suggest
    - search.highlight
  language: zh

nav:
  - 算法打卡: http://alg.haohaha.cn
  - 数学笔记: http://math.haohaha.cn
  - 英语笔记: http://eng.haohaha.cn
  - CS笔记: 
    - Intro: index.md
    - 408:
      - arch:
        - 2.数据的表示与运算:
          - 2.1_数制与编码: 408/arch/2-1.md
          - 2.2_运算方法和运算电路: 408/arch/2-2.md
          - 2.3_浮点数的表示与运算: 408/arch/2-3.md
        - 3.存储系统:
          - 3.1_存储器概述: 408/arch/3-1.md
          - 3.2_主存储器: 408/arch/3-2.md
          - 3.3_主存储器与CPU的连接: 408/arch/3-3.md
          - 3.4_外部存储器: 408/arch/3-4.md
          - 3.5_高速缓冲存储器: 408/arch/3-5.md
          - 3.6_虚拟存储器: 408/arch/3-6.md
      - os:
#       - 3.内存管理: 
#         - 3.1_内存管理概念: 408/os/3-1.md
#         - 3.2_虚拟内存管理: 408/os/3-2.md
#       - 4.文件管理: 
#         - 4.1_文件系统基础: 408/os/4-1.md
#         - 4.2_目录: 408/os/4-2.md
#         - 4.3_文件系统: 408/os/4-3.md
        - 5.输入/输出（I/O）管理: 
          - 5.3_磁盘和固态硬盘: 408/os/5-3.md
#     - nwk:
#     - dsa:
#   - HJCPP: 
#     - 01.OOP1: hjcpp/01.md
    - MicroFrank:  
      - MySQL:  
        - 01.MySQL安装与初始化: frank/mysql/01.md 
        - 02.数据库的基本操作: frank/mysql/02.md 
        - 03.表的基本操作: frank/mysql/03.md
        - 04.数据操作: frank/mysql/04.md
        - 05.数据类型: frank/mysql/05.md
#   - Linux高性能服务器编程: 
#     - 第一篇 TCP/IP详解: 
#       - 第1章 TCP/IP协议族: hpsc/01/01.md 
  - 我爱OS: http://os.haohaha.cn 
  - 闲聊波尔卡: http://chat.haohaha.cn 
extra_css:
  - mkdocs/css/no-footer.css # 不使用底部的翻页
extra:
  homepage: http://haohaha.cn
  social: # icons
    - icon: fontawesome/brands/bilibili
      link: https://space.bilibili.com/1436476753
      name: Bilibili | 浩哈哈哈哈 # 鼠标悬浮提示
    - icon: fontawesome/brands/github
      link: https://github.com/Haohahahaha
      name: GitHub | Haohahahaha
## [bottom-left corner]
copyright: Copyright &copy; 2022 浩哈哈哈哈_ # 左下角的版权声明
