site_name: 浩哈哈哈哈
theme: 
  name: material
  icon:
    logo: material/noodles
  favicon: https://cs.haohaha.cn/image/favicon.png
#     admonition:
  palette:
    - scheme: slate # 夜间模式
      primary: deep purple
      accent: deep orange
      toggle:
        icon: material/weather-sunny
        name: 切换至日间模式
    - scheme: default # 日间模式
      primary: deep purple # 上方的
      accent: deep orange # 链接等可交互元件的高亮色
      toggle:
        icon: material/weather-night # 图标
        name: 切换至夜间模式 # 鼠标悬浮提示
  features:
    - navigation.tabs
    - navigation.top
    - navigation.indexes
    - navigation.expand
#   - navigation.prune
    - search.suggest
    - search.highlight
    - content.code.copy
    # Instant Loading
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    # Anchor tracking
    - navigation.tracking
    
  language: zh

edit_uri: edit/main/docs

nav:
  - 主页: http://haohaha.cn
  - CS笔记: 
    - index.md
    - GreenHand菜鸟:
      - OSCA招生简章: greenhand/recruit/recruit.md
      - 2023-培养方案:
        - 个人成长路线-beta: greenhand/fertile/fertile.md
        - 2023年度考核标准: greenhand/fertile/assessment-2023.md
      - 信息的编解码能力: greenhand/de-en-code/de-en-code-info.md
      - 提问の二三事: greenhand/ask-question-zbt/ask-zbt.md
      - Ubuntu 安装系列:
        - Ubuntu 22.04 虚拟机自动化安装 (initializer-ubuntu2204使用教程): greenhand/initializer-ubuntu2204/install.md
        - Ubuntu 22.04 虚拟机搭建全流程: greenhand/Ubuntu2204-greenhand/Ubuntu2204-greenhand.md
        - Ubuntu 22.04 我的第一台实体机: greenhand/Ubuntu2204-myFirstPhysicalLinuxMachine/U2204-mFPLM.md
      - 基于 mkdocs-material 的个人博客搭建: greenhand/initializer-material-blog/blog-init.md
      - jyyslide-md-scripts 安装指南: greenhand/jyyslide-md-script/install.md
    - bLog:
      - Admonitions: blog/admonitions/admonitions.md
    - uCore OS experiment instructions:
      - Introduction: ucore-EI/README.md
      - LAB0：ready~go!: 
        - ucore-EI/Lab0/README.md
        - 实验目的: ucore-EI/Lab0/实验目的.md
        - 实验内容: ucore-EI/Lab0/实验内容.md
        - 前导知识: 
          - ucore-EI/Lab0/前导知识.md
          - 了解uCore: ucore-EI/Lab0/前导知识/了解uCore.md
          - 了解RISC-V: ucore-EI/Lab0/前导知识/了解RISC-V.md
          - 了解OS实验: ucore-EI/Lab0/前导知识/了解OS实验.md
          - 了解实验环境: ucore-EI/Lab0/前导知识/了解实验环境.md
          - 了解开发调试基本工具: ucore-EI/Lab0/前导知识/了解开发调试基本工具.md
          - 了解硬件模拟器: ucore-EI/Lab0/前导知识/了解硬件模拟器.md
        - 设置实验环境: ucore-EI/Lab0/设置实验环境.md
        - 配置环境: 
          - ucore-EI/Lab0/配置环境.md
          - 安装虚拟环境: ucore-EI/Lab0/配置环境/安装虚拟环境.md
          - 安装开发工具: ucore-EI/Lab0/配置环境/安装开发工具.md
          - 安装硬件模拟器: ucore-EI/Lab0/配置环境/安装硬件模拟器.md
          - 安装调试工具: ucore-EI/Lab0/配置环境/安装调试工具.md
      - LAB0.5：最小可执行内核:
        - ucore-EI/Lab0.5/README.md 
        - 实验目的: ucore-EI/Lab0.5/实验目的.md
        - 实验内容: ucore-EI/Lab0.5/实验内容.md
        - 练习: ucore-EI/Lab0.5/练习.md
        - 内存布局: ucore-EI/Lab0.5/内存布局.md
        - 链接脚本: ucore-EI/Lab0.5/链接脚本.md
        - 真正的入口点: ucore-EI/Lab0.5/真正的入口点.md
        - 从SBI到stdio: ucore-EI/Lab0.5/从SBI到stdio.md
        - 编译运行: ucore-EI/Lab0.5/编译运行.md
        - 项目组成与执行流: ucore-EI/Lab0.5/项目组成与执行流.md
      - LAB1：中断机制:
        - ucore-EI/Lab1/README.md
        - 实验目的: ucore-EI/Lab1/实验目的.md
        - 实验内容: ucore-EI/Lab1/实验内容.md
        - 练习: ucore-EI/Lab1/练习.md
        - RISC-V中断相关: ucore-EI/Lab1/RISC-V中断相关.md
        - 上下文处理: ucore-EI/Lab1/上下文处理.md
        - 中断处理程序: ucore-EI/Lab1/中断处理程序.md
        - 时钟中断: ucore-EI/Lab1/时钟中断.md
        - 项目组成与执行流: ucore-EI/Lab1/项目组成与执行流.md
      - LAB2：物理内存管理:
        - ucore-EI/Lab2/README.md 
        - 实验目的: ucore-EI/Lab2/实验目的.md
        - 实验内容: ucore-EI/Lab2/实验内容.md
        - 练习: ucore-EI/Lab2/练习.md
        - 地址与页表: ucore-EI/Lab2/地址与页表.md
        - 物理内存探测: ucore-EI/Lab2/物理内存探测.md
        - 以页为单位管理物理内存: ucore-EI/Lab2/以页为单位管理物理内存.md
        - 页面分配算法: ucore-EI/Lab2/页面分配算法.md
        - 项目组成与执行流: ucore-EI/Lab2/项目组成与执行流.md
      - LAB3：虚拟内存管理:
        - ucore-EI/Lab3/README.md 
        - 实验目的: ucore-EI/Lab3/实验目的.md
        - 实验内容: ucore-EI/Lab3/实验内容.md
        - 练习: ucore-EI/Lab3/练习.md
        - 页面置换: ucore-EI/Lab3/页面置换.md
        - PageFault: ucore-EI/Lab3/PageFault.md
        - 使用多级页表: ucore-EI/Lab3/使用多级页表.md
        - 页面置换机制: ucore-EI/Lab3/页面置换机制.md
        - FIFO置换算法: ucore-EI/Lab3/FIFO置换算法.md
        - 项目组成与执行流: ucore-EI/Lab3/项目组成与执行流.md
      - LAB4：进程管理:
        - ucore-EI/Lab4/README.md 
        - 实验目的: ucore-EI/Lab4/实验目的.md
        - 实验内容: ucore-EI/Lab4/实验内容.md
        - 练习: ucore-EI/Lab4/练习.md
        - 进程与线程: ucore-EI/Lab4/进程与线程.md
        - 相关结构体: ucore-EI/Lab4/相关结构体.md
        - 进程模块初始化: ucore-EI/Lab4/进程模块初始化.md
        - 进程切换: ucore-EI/Lab4/进程切换.md
        - 项目组成与执行流: ucore-EI/Lab4/项目组成与执行流.md
      - LAB5：用户程序:
        - ucore-EI/Lab5/README.md 
        - 实验目的: ucore-EI/Lab5/实验目的.md
        - 实验内容: ucore-EI/Lab5/实验内容.md
        - 练习: ucore-EI/Lab5/练习.md
        - 用户进程: ucore-EI/Lab5/用户进程.md
        - 用户程序: ucore-EI/Lab5/用户程序.md
        - 创建并执行用户进程: ucore-EI/Lab5/创建并执行用户进程.md
        - 系统调用: ucore-EI/Lab5/系统调用.md
        - 用户进程的退出和等待: ucore-EI/Lab5/用户进程的退出和等待.md
        - 项目组成与执行流: ucore-EI/Lab5/项目组成与执行流.md
      - LAB6：进程调度:
        - ucore-EI/Lab6/README.md 
        - 实验目的: ucore-EI/Lab6/实验目的.md
        - 实验内容: ucore-EI/Lab6/实验内容.md
        - 练习: ucore-EI/Lab6/练习.md
        - 进程状态: ucore-EI/Lab6/进程状态.md
        - 再次认识进程切换: ucore-EI/Lab6/再次认识进程切换.md
        - 调度算法框架: ucore-EI/Lab6/调度算法框架.md
        - 项目组成与执行流: ucore-EI/Lab6/项目组成与执行流.md
      - LAB7：同步互斥:
        - ucore-EI/Lab7/README.md 
        - 实验目的: ucore-EI/Lab7/实验目的.md
        - 实验内容: ucore-EI/Lab7/实验内容.md
        - 练习: ucore-EI/Lab7/练习.md
        - 同步互斥的基本概念: ucore-EI/Lab7/同步互斥的基本概念.md
        - 信号量: ucore-EI/Lab7/信号量.md
        - 条件变量与管程: ucore-EI/Lab7/条件变量与管程.md
        - 项目组成与执行流: ucore-EI/Lab7/项目组成与执行流.md
      - LAB8：文件系统:
        - ucore-EI/Lab/README.md 
        - 实验目的: ucore-EI/Lab/实验目的.md
        - 实验内容: ucore-EI/Lab/实验内容.md
        - 练习: ucore-EI/Lab/练习.md
        - 文件系统介绍: ucore-EI/Lab/文件系统介绍.md
        - 文件系统抽象层VFS: ucore-EI/Lab/文件系统抽象层VFS.md
        - 硬盘文件系统SFS: ucore-EI/Lab/硬盘文件系统SFS.md
        - 设备即文件: ucore-EI/Lab/设备即文件.md
        - 从中断到终端: ucore-EI/Lab/从中断到终端.md
        - 项目组成与执行流: ucore-EI/Lab/项目组成与执行流.md
    - 408:
      - arch:
        - 1.计算机系统概述:
          - 1.1_计算机发展历程: 408/arch/1-1.md
          - 1.2_计算机系统层次结构: 408/arch/1-2.md
          - 1.3_计算机的性能指标: 408/arch/1-3.md
        - 2.数据的表示与运算:
          - 2.1_数制与编码: 408/arch/2-1.md
          - 2.2_运算方法和运算电路: 408/arch/2-2.md
          - 2.3_浮点数的表示与运算: 408/arch/2-3.md
        - 3.存储系统:
          - 3.1_存储器概述: 408/arch/3-1.md
          - 3.2_主存储器: 408/arch/3-2.md
          - 3.3_主存储器与CPU的连接: 408/arch/3-3.md
          - 3.4_外部存储器: 408/arch/3-4.md
          - 3.5_高速缓冲存储器: 408/arch/3-5.md
          - 3.6_虚拟存储器: 408/arch/3-6.md
        - 4.指令系统:
          - 4.1_指令格式: 408/arch/4-1.md
          - 4.2_指令的寻址方式: 408/arch/4-2.md
          - 4.3_程序的机器级代码表示: 408/arch/4-3.md
          - 4.4_CISC和RISC的基本概念: 408/arch/4-4.md
        - 5.中央处理器:
          - 5.1_CPU的功能和基本结构: 408/arch/5-1.md
          - 5.2_指令执行过程: 408/arch/5-2.md
          - 5.3_数据通路的功能和基本结构: 408/arch/5-3.md
          - 5.4_控制器的功能和工作原理: 408/arch/5-4.md
          - 5.5_异常和中断机制: 408/arch/5-5.md
          - 5.6_指令流水线: 408/arch/5-6.md
          - 5.7_多处理器的基本概念: 408/arch/5-7.md
        - 6.总线:
          - 6.1_总线概述: 408/arch/6-1.md
          - 6.2_总线事务和定时: 408/arch/6-2.md
        - 7.输入/输出系统:
          - 7.1_I/O系统基本概念: 408/arch/7-1.md
          - 7.2_I/O接口: 408/arch/7-2.md
          - 7.3_I/O方式: 408/arch/7-3.md
      - os:
        - 1.计算机系统概述:
#         - 1.1_操作系统的基本概念: 408/os/1-1.md
#         - 1.2_操作系统发展历程: 408/os/1-2.md
#         - 1.3_操作系统运行环境: 408/os/1-3.md
#         - 1.4_操作系统结构: 408/os/1-4.md
          - 1.5_操作系统引导: 408/os/1-5.md
          - 1.6_虚拟机: 408/os/1-6.md
        - 2.进程与线程:
          - 2.1_进程与线程: 408/os/2-1.md
          - 2.2_处理机调度: 408/os/2-2.md
#         - 2.3_同步与互斥: 408/os/2-3.md
#         - 2.4_死锁: 408/os/2-4.md
        - 3.内存管理: 
          - 3.1_内存管理概念: 408/os/3-1.md
          - 3.2_虚拟内存管理: 408/os/3-2.md
        - 4.文件管理: 
          - 4.1_文件系统基础: 408/os/4-1.md
          - 4.2_目录: 408/os/4-2.md
          - 4.3_文件系统: 408/os/4-3.md
        - 5.输入/输出（I/O）管理: 
#         - 5.1_I/O管理概述: 408/os/5-1.md
#         - 5.2_设备独立性软件: 408/os/5-2.md
          - 5.3_磁盘和固态硬盘: 408/os/5-3.md
      - nwk:
#       - 1.计算机网络体系结构:
#         - 1.1_计算机网络概述: 408/nwk/1-1.md
#         - 1.2_计算机网络体系结构与参与模型: 408/mwk/1-2.md
#       - 2.物理层:
#         - 2.1_通信基础: 408/nwk/2-1.md
#         - 2.2_传输介质: 408/nwk/2-2.md
#         - 2.3_物理层设备: 408/nwk/2-3.md
        - 3.数据链路层:
          - 3.1_数据链路层的功能: 408/nwk/3-1.md
          - 3.2_组帧: 408/nwk/3-2.md
#         - 3.3_差错控制: 408/nwk/3-3.md
#         - 3.4_流量控制与可靠传输机制: 408/nwk/3-4.md
#         - 3.5_介质访问控制: 408/nwk/3-5.md
#         - 3.6_局域网: 408/nwk/3-6.md
#         - 3.7_广域网: 408/nwk/3-7.md
#         - 3.8_数据链路层设备: 408/nwk/3-8.md
#       - 4.网络层:
#         - 4.1_网络层的功能: 408/nwk/4-1.md
#         - 4.2_路由算法: 408/nwk/4-2.md
#         - 4.3_IPv4: 408/nwk/4-3.md
#         - 4.4_IPv6: 408/nwk/4-4.md
#         - 4.5_路由协议: 408/nwk/4-5.md
#         - 4.6_IP组播: 408/nwk/4-6.md
#         - 4.7_移动IP: 408/nwk/4-7.md
#         - 4.8_网络层设备: 408/nwk/4-8.md
#       - 5.传输层:
#         - 5.1_传输层提供的服务: 408/nwk/5-1.md
#         - 5.2_UDP协议: 408/nwk/5-2.md
#         - 5.3_TCP协议: 408/nwk/5-3.md
#       - 6.应用层:
#         - 6.1_网络应用模型: 408/nwk/6-1.md
#         - 6.2_域名系统(DNS): 408/nwk/6-2.md
#         - 6.3_文件传输协议(FTP): 408/nwk/6-3.md
#         - 6.4_电子邮件: 408/nwk/6-4.md
#         - 6.5_万维网(WWW): 408/nwk/6-5.md
#     - dsa:
#       - 1.绪论:
#         - 1.1_数据结构的基本概念: 408/dsa/1-1.md
#         - 1.2_算法和算法评价: 408/dsa/1-2.md
#       - 2.线性表:
#         - 2.1_线性表的定义和基本操作: 408/dsa/2-1.md
#         - 2.2_线性表的顺序表示: 408/dsa/2-2.md
#         - 2.3_线性表的链式表示: 408/dsa/2-3.md
#       - 3.栈、队列和数组:
#         - 3.1_栈: 408/dsa/3-1.md
#         - 3.2_队列: 408/dsa/3-2.md
#         - 3.3_栈和队列的应用: 408/dsa/3-3.md
#         - 3.4_数组和特殊矩阵: 408/dsa/3-4.md
#       - 4.串:
#         - 4.1_串的定义和实现: 408/dsa/4-1.md
#         - 4.2_串的模式匹配: 408/dsa/4-2.md
#       - 5.树与二叉树:
#         - 5.1_树的基本概念: 408/dsa/5-1.md
#         - 5.2_二叉树的概念: 408/dsa/5-2.md
#         - 5.3_二叉树的遍历和线索二叉树: 408/dsa/5-3.md
#         - 5.4_树、森林: 408/dsa/5-4.md
#         - 5.5_树与二叉树的应用: 408/dsa/5-5.md
#       - 6.图:
#         - 6.1_图的基本概念: 408/dsa/6-1.md
#         - 6.2_图的存储及基本操作: 408/dsa/6-2.md
#         - 6.3_图的遍历: 408/dsa/6-3.md
#         - 6.4_图的应用: 408/dsa/6-4.md
#       - 7.查找:
#         - 7.1_查找的基本概念: 408/dsa/7-1.md
#         - 7.2_顺序查找和折半查找: 408/dsa/7-2.md
#         - 7.3_树型查找: 408/dsa/7-3.md
#         - 7.4_B树和B+树: 408/dsa/7-4.md
#         - 7.5_散列表: 408/dsa/7-5.md
#       - 8.排序:
#         - 8.1_排序的基本概念: 408/dsa/8-1.md
#         - 8.2_插入排序: 408/dsa/8-2.md
#         - 8.3_交换排序: 408/dsa/8-3.md
#         - 8.4_选择排序: 408/dsa/8-4.md
#         - 8.5_归并排序和基数排序: 408/dsa/8-5.md
#         - 8.6_各种内部排序算法的比较及应用: 408/dsa/8-6.md
#         - 8.7_外部排序: 408/dsa/8-7.md
#   - HJCPP: 
#     - 01.OOP1: hjcpp/01.md
    - Git:
      - 多分支仓库的创建与上传: git/2023-05-12_git_branch.md
    - 学术会议记录: 
      - 简介: conferenceNotes/index.md
      - 大力开展基于国产AI芯片的大模型系统的研究: conferenceNotes/大力开展基于国产AI芯片的大模型系统的研究.md
  - 闲聊波尔卡: http://chat.haohaha.cn 
  - OS学习: http://os.haohaha.cn 
  - 算法打卡: http://alg.haohaha.cn
  - 数学笔记: http://math.haohaha.cn
  - 英语笔记: http://eng.haohaha.cn

extra_css:
  - mkdocs/css/no-footer.css # 不使用底部的翻页
  - mkdocs/extra_admonition.css # 自定义admonition

markdown_extensions:
    # Admonitions
    - admonition
    - pymdownx.details
    - pymdownx.superfences
    # Icons, Emojis
    - attr_list
    - pymdownx.emoji:
        emoji_index: !!python/name:material.extensions.emoji.twemoji
        emoji_generator: !!python/name:material.extensions.emoji.to_svg
    # Formatting
    - pymdownx.critic
    - pymdownx.caret
    - pymdownx.keys
    - pymdownx.mark
    - pymdownx.tilde
    # Diagrams
    - pymdownx.superfences:
        custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_code_format

extra:
  homepage: http://haohaha.cn
  social: # icons
    - icon: fontawesome/brands/bilibili
      link: https://space.bilibili.com/1436476753
      name: Bilibili | 浩哈哈哈哈 # 鼠标悬浮提示
    - icon: fontawesome/brands/github
      link: https://github.com/Haohahahaha
      name: GitHub | Haohahahaha
    - icon: simple/githubactions
      link: https://github.com/Haohahahaha/cs/actions
      name: GitHub Actions
## [bottom-left corner]
copyright: Copyright &copy; 2022-现在 浩哈哈哈哈_ # 左下角的版权声明
