site_name: CS笔记
theme: 
  name: material
  icon:
    logo: material/library
  palette:
    - scheme: slate # 夜间模式
      primary: indigo
      accent: orange
      toggle:
        icon: material/weather-sunny
        name: 切换至日间模式
    - scheme: default # 日间模式
      primary: indigo # 上方的
      accent: orange # 链接等可交互元件的高亮色
      toggle:
        icon: material/weather-night # 图标
        name: 切换至夜间模式 # 鼠标悬浮提示
  features:
    - navigation.tabs
    - navigation.top
    - navigation.indexes
    - navigation.expand
    - search.suggest
    - search.highlight
  language: zh

nav:
  - 算法打卡: http://alg.haohaha.cn
  - 数学笔记: http://math.haohaha.cn
  - 英语笔记: http://eng.haohaha.cn
  - CS笔记: 
    - Home: index.md
    - HJ_CPP: hjcpp/index.md
      - 01.OOP_1: hjcpp/01.md
    - MicroFrank: frank/index.md
      - MySQL: frank/mysql/index.md
        - 01.MySQL安装与初始化: frank/mysql/01.md
        - 02.数据库的基本操作: frank/mysql/02.md
    - Linux高性能服务器编程: hpsc/index.md
      - 第一篇 TCP/IP详解:
        - 第1章 TCP/IP协议族: hpsc/01/01.md
    - 计算机网络: nwk/index.md
      - 0x00_应用层: nwk/0x00.md 
  - 我爱OS: http://os.haohaha.cn
  - 闲聊波尔卡: http://chat.haohaha.cn 
extra_css:
  - mkdocs/css/no-footer.css # 不使用底部的翻页
extra:
  homepage: http://haohaha.cn
  social: # icons
    - icon: fontawesome/brands/bilibili
      link: https://space.bilibili.com/1436476753
      name: Bilibili | 浩哈哈哈哈 # 鼠标悬浮提示
    - icon: fontawesome/brands/github
      link: https://github.com/Haohahahaha
      name: GitHub | Haohahahaha
## [bottom-left corner]
copyright: Copyright &copy; 2022 浩哈哈哈哈_ # 左下角的版权声明
