site_name: 浩哈哈哈哈
theme: 
  name: material
  icon:
    logo: material/noodles
  favicon: https://cs.haohaha.cn/image/favicon.png
#     admonition:
  palette:
    - scheme: slate # 夜间模式
      primary: deep purple
      accent: deep orange
      toggle:
        icon: material/weather-sunny
        name: 切换至日间模式
    - scheme: default # 日间模式
      primary: deep purple # 上方的
      accent: deep orange # 链接等可交互元件的高亮色
      toggle:
        icon: material/weather-night # 图标
        name: 切换至夜间模式 # 鼠标悬浮提示
  features:
    - navigation.tabs
    - navigation.top
    - navigation.indexes
    - navigation.expand
    - navigation.prune # 折叠
    - search.suggest
    - search.highlight
    - content.code.copy
    # Instant Loading
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    # Anchor tracking
    - navigation.tracking
    
  language: zh

edit_uri: edit/main/docs

nav:
  - Home: http://haohaha.cn
  - Be_Rational: 
    - index.md
    - YSYX:
      - ysyx/index.md
      - 0116-预学习-1: ysyx/0116/log.md
      - 0120-预学习-2.(1): ysyx/0120/log.md
      - 0121-预学习-2.(2): ysyx/0121/log.md
      - 0122-预学习-2.(3): ysyx/0122/log.md
      - 0302-预学习-2&4: ysyx/0302/log.md
      - 0303-预学习-4.(1): ysyx/0303/log.md
      - 0304-预学习-4.(2): ysyx/0304/log.md
      - 0324-预学习-4.(3): ysyx/0304/log.md
    - 信息沟通: 
      - 信息的编解码能力: greenhand/de-en-code/de-en-code-info.md
      - 提问の二三事: greenhand/ask-question-zbt/ask-zbt.md
    - Ubuntu 系列:
      - Ubuntu 22.04 虚拟机自动化安装 (initializer-ubuntu2204使用教程): greenhand/initializer-ubuntu2204/install.md
      - Ubuntu 22.04 虚拟机搭建全流程: greenhand/Ubuntu2204-greenhand/Ubuntu2204-greenhand.md
      - Ubuntu 22.04 我的第一台实体机: greenhand/Ubuntu2204-myFirstPhysicalLinuxMachine/U2204-mFPLM.md
      - Ubuntu 22.04 远程桌面: greenhand/Ubuntu-Remote-Desktop/URD.md
    - 博客 系列: 
      - 基于 mkdocs-material 的个人博客搭建: greenhand/initializer-material-blog/blog-init.md
      - PPT_jyyslide-md-scripts 安装指南: greenhand/jyyslide-md-script/install.md
      - VitePress 尝试の大失败: greenhand/VitePress-Failed/nonono.md
      - Admonitions: blog/admonitions/admonitions.md
#     - 个人效率提升指南: greenhand/efficient/efficient.md
    - 服务器虚拟化搭建 系列:
      - 核显直通笔记: Server/AIO/AIO-CoreGPU-Passthrough.md
      - PVE-服务器部署: Server/AIO/PVE-Server-install.md
      - All in One 服务器配置流程: Server/AIO/All-in-One-Server.md
      - PVE 中 local 盘空间不足的解决办法: Server/AIO/AIO-Disk.md
      - 本地服务器远程连接: Server/Remote-SSH-to-LocalMachine.md
      - 在服务器内使用 Docker 建立 Nextcloud 私有云: Server/nextcloud-docker.md
      - SSL证书部署or更新流程: Server/ssl-update.md
      - Git-多分支仓库的创建与上传: git/git_branch.md
  - Chat_Polka: http://chat.haohaha.cn 
  - Algorithm: http://alg.haohaha.cn

extra_css:
  - mkdocs/css/no-footer.css # 不使用底部的翻页
  - mkdocs/extra_admonition.css # 自定义admonition

markdown_extensions:
    # Admonitions
    - admonition
    - pymdownx.details
    - pymdownx.superfences
    # Icons, Emojis
    - attr_list
    - pymdownx.emoji:
        emoji_index: !!python/name:material.extensions.emoji.twemoji
        emoji_generator: !!python/name:material.extensions.emoji.to_svg
    # Formatting
    - pymdownx.critic
    - pymdownx.caret
    - pymdownx.keys
    - pymdownx.mark
    - pymdownx.tilde
    # Diagrams
    - pymdownx.superfences:
        custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_code_format
    - pymdownx.tasklist:
        custom_checkbox: true

extra:
  homepage: http://haohaha.cn
  social: # icons
    - icon: fontawesome/brands/bilibili
      link: https://space.bilibili.com/1436476753
      name: Bilibili | 浩哈哈哈哈 # 鼠标悬浮提示
    - icon: fontawesome/brands/github
      link: https://github.com/Haohahahaha
      name: GitHub | Haohahahaha
    - icon: simple/githubactions
      link: https://github.com/Haohahahaha/cs/actions
      name: GitHub Actions
## [bottom-left corner]
copyright: 
  <a href="https://beian.miit.gov.cn/" target="_blank">冀ICP备2024078994号</a><br/>
  <a href="http://www.beian.gov.cn/portal/registerSystemInfo?recordcode=13020302001386" target="_blank">冀公网安备13020302001386号</a><br/>
  Copyright &copy; 2022-现在 浩哈哈哈哈_ # 左下角的版权声明