site_name: 浩哈哈哈哈
theme: 
  name: material
  icon:
    logo: material/noodles
  favicon: https://cs.haohaha.cn/image/favicon.png
#     admonition:
  palette:
    - scheme: slate # 夜间模式
      primary: deep purple
      accent: deep orange
      toggle:
        icon: material/weather-sunny
        name: 切换至日间模式
    - scheme: default # 日间模式
      primary: deep purple # 上方的
      accent: deep orange # 链接等可交互元件的高亮色
      toggle:
        icon: material/weather-night # 图标
        name: 切换至夜间模式 # 鼠标悬浮提示
  features:
    - navigation.tabs
    - navigation.top
    - navigation.indexes
    - navigation.expand
    - navigation.prune # 折叠
    - search.suggest
    - search.highlight
    - content.code.copy
    # Instant Loading
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    # Anchor tracking
    - navigation.tracking
    
  language: zh

edit_uri: edit/main/docs

nav:
  - Home: http://haohaha.cn
  - Be_Rational: 
    - index.md
    - 编程:
      - YSYX: 00-code/01-ysyx/index.md
      - Rust: 00-code/02-Rust/Rust_Learning.md
    - 信息沟通: 
      - 信息的编解码能力: 01-info_communication/01-de_en_code/info.md
      - 提问の二三事: 01-info_communication/02-ask_question/zbt.md
    - Ubuntu 系列:
      - Ubuntu 22.04 虚拟机自动化安装 (initializer-ubuntu2204使用教程): 02-ubuntu/01-initializer/install.md
      - Ubuntu 22.04 虚拟机搭建全流程: 02-ubuntu/02-nanny/tutorial.md
      - Ubuntu 22.04 我的第一台实体机: 02-ubuntu/03-1stPhysical/Machine.md
      - Ubuntu 22.04 远程桌面: 02-ubuntu/04-Remote/Desktop.md
    - 博客 系列: 
      - 基于 mkdocs-material 的个人博客搭建: 03-blog/01-init/tutorial.md
      - PPT_jyyslide-md-scripts 安装指南: 03-blog/02-PPT_Plus/install.md
      - VitePress 尝试の大失败: 03-blog/03-VitePress/nonono.md
      - Admonitions: 03-blog/04-admonitions/config.md
#     - 个人效率提升指南: 03-blog/efficient/efficient.md
    - 服务器虚拟化搭建 系列:
      - 04-Server/index.md
      - All in One 服务器配置流程: 04-Server/01-AIO_Server.md
      - PVE-服务器部署: 04-Server/02-PVE_deploy.md
      - 核显直通笔记: 04-Server/03-CoreGPU_Passthrough.md
      - PVE 中 local 盘空间不足的解决办法: 04-Server/04-PVE_Disk.md
      - 本地服务器远程连接: 04-Server/05-SSH_Remote_Local.md
      - 在服务器内使用 Docker 建立 Nextcloud 私有云: 04-Server/06-nextcloud_docker.md
      - SSL证书部署or更新流程: 04-Server/07-ssl_update.md
      - Git-多分支仓库的创建与上传: 04-Server/git/git_branch.md
    - 移动设备:
      - 05-mobile/index.md
      - 基于 红米 5 Plus 的 刷机优化流程: 05-mobile/01-Redmi5P-PE11.md
  - Chat_Polka: http://chat.haohaha.cn 
  - Algorithm: http://alg.haohaha.cn

extra_css:
  - mkdocs/css/no-footer.css # 不使用底部的翻页
  - mkdocs/extra_admonition.css # 自定义admonition

markdown_extensions:
    # Admonitions
    - admonition
    - pymdownx.details
    - pymdownx.superfences
    # Icons, Emojis
    - attr_list
    - pymdownx.emoji:
        emoji_index: !!python/name:material.extensions.emoji.twemoji
        emoji_generator: !!python/name:material.extensions.emoji.to_svg
    # Formatting
    - pymdownx.critic
    - pymdownx.caret
    - pymdownx.keys
    - pymdownx.mark
    - pymdownx.tilde
    # Diagrams
    - pymdownx.superfences:
        custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_code_format
    - pymdownx.tasklist:
        custom_checkbox: true

extra:
  homepage: http://haohaha.cn
  social: # icons
    - icon: fontawesome/brands/bilibili
      link: https://space.bilibili.com/1436476753
      name: Bilibili | 浩哈哈哈哈 # 鼠标悬浮提示
    - icon: fontawesome/brands/github
      link: https://github.com/Haohahahaha
      name: GitHub | Haohahahaha
    - icon: simple/githubactions
      link: https://github.com/Haohahahaha/cs/actions
      name: GitHub Actions
## [bottom-left corner]
copyright: 
  <a href="https://beian.miit.gov.cn/" target="_blank">冀ICP备2024078994号</a><br/>
  <a href="http://www.beian.gov.cn/portal/registerSystemInfo?recordcode=13020302001386" target="_blank">冀公网安备13020302001386号</a><br/>
  Copyright &copy; 2022-现在 浩哈哈哈哈_ # 左下角的版权声明